version: '3.8'
services:
  api-student-06:
    build: .
    ports:
      - "3006:3000"
    environment:
      DB_URL: mongodb://mongo-student-06:27017/CRMdb-student-06
      PORT: 3000
    depends_on:
      - mongo-student-06
  mongo-student-06:
    image: mongo:latest
    ports:
      - "27023:27017"
    volumes:
      - db-data-student-06:/data/db
volumes:
  db-data-student-06:
